messages = []
messages.append("1")
messages.append("2")
messages.append("3")
messages.append("10")
messages.append("20")
messages.append("30")
print(messages)
messages.pop(1)
messages.pop(1)
print(messages)